Primeiro CRUD/Models/ErrorViewModel.cs
using System;

namespace Primeiro_CRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Primeiro CRUD/Models/Instituicao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Primeiro_CRUD.Models
{
    public class Instituicao
    {
        public long? InstituicaoID { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
    }
}

Primeiro CRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Primeiro_CRUD.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Primeiro_CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Primeiro CRUD/Controllers/InstituicaoController.cs
using Primeiro_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Primeiro_CRUD.Controllers
{
    public class InstituicaoController : Controller
    {
        private static IList<Instituicao> instituicoes =
            new List<Instituicao>()
                {
                    new Instituicao(){
                        InstituicaoID = 1,
                        Nome = "UniParaná",
                        Endereco = "Paraná"
                    },
                    new Instituicao(){
                        InstituicaoID = 2,
                        Nome = "UniSanta",
                        Endereco = "Santa Catarina"
                    },
                    new Instituicao(){
                        InstituicaoID = 3,
                        Nome = "UniSãoPaulo",
                        Endereco = "São Paulo"
                    },
                    new Instituicao(){
                        InstituicaoID = 4,
                        Nome = "UniSulGrandense",
                        Endereco = "Rio Grande do Sul"
                    },
                    new Instituicao(){
                        InstituicaoID = 5,
                        Nome = "UniCarioca",
                        Endereco = "Rio de Janeiro"
                    },
                };
        // Definição de uma action chamada Index
        public IActionResult Index()
        {
            return View(instituicoes.OrderBy(i => i.InstituicaoID));
        }

        //GET: Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Instituicao instituicao)
        {
            instituicoes.Add(instituicao);
            instituicao.InstituicaoID = instituicoes.Select(i => i.InstituicaoID).Max() + 1;
            return RedirectToAction("Index");
        }

        public ActionResult Edit(long id)
        {
            return View(instituicoes.Where(i => i.InstituicaoID == id).First());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Instituicao instituicao)
        {
            instituicoes[instituicoes.IndexOf(instituicoes.Where(
                i => i.InstituicaoID == instituicao.InstituicaoID).First())] = instituicao;
            return RedirectToAction("Index");
        }

        public ActionResult Details(long id)
        {
            return View(instituicoes.Where(i => i.InstituicaoID == id).First());
        }

        public ActionResult Delete(long id)
        {
            return View(instituicoes.Where(i => i.InstituicaoID == id).First());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Instituicao instituicao)
        {
            instituicoes.Remove(instituicoes.Where(i => i.InstituicaoID == instituicao.InstituicaoID).First());
            return RedirectToAction("Index");
        }

    }
}

Primeiro CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home - ASP.NET Core MVC";
    Layout = "~/Views/Shared/_LayoutIES.cshtml";
}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="mx-auto d-block w-75" src="~/images/linux-programing.png" alt="Linux">
        </div>
        <div class="carousel-item">
            <img class="mx-auto d-block w-75" src="~/images/laptop-programing.jpg" alt="Laptop">
        </div>
    </div>
</div>

Primeiro CRUD/Views/Instituicao/Create.cshtml
@model Primeiro_CRUD.Models.Instituicao
@{
    Layout = "_LayoutIES";
}
<div class="card-block">
    <div class="card-header text-white bg-danger text-center h1">
        Registrando uma nova instituição
    </div>
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group text-center h3">
                <input type="submit" value="Registrar Instituição"class="btn btn-light" />
                <a asp-action="Index" class="btn btn-info">Retornar à listagem de instituições</a>
            </div>
        </form>
    </div>
    <div class="card-footer bg-dark text-center text-white">
        Informe os dados acima e/ou clique em um dos botões de ação
    </div>
</div>
@section ScriptPage {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Primeiro CRUD/Views/Instituicao/Delete.cshtml
@model Primeiro_CRUD.Models.Instituicao
@{
    Layout = "_LayoutIES";
}
@section Styles {
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
}
<div class="card-block">
    <div class="card-header text-white bg-secondary text-center h1">
    Exibindo uma instituição existente
    </div>
    <div class="card-body">
        <div class="form-group">
            <label asp-for="InstituicaoID" class="control-label">
            </label>
            <br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </span>
                <input asp-for="InstituicaoID" class="form-control" disabled="disabled" />
            </div>
            <label asp-for="Nome" class="control-label"></label>
            <br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                </span>
                <input asp-for="Nome" class="form-control" disabled="disabled" />
            </div>
            <label asp-for="Endereco" class="control-label"></label>
                <br />
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-address-card-o" aria-hidden="true"></i>
                    </span>
                    <input asp-for="Endereco" class="form-control" disabled="disabled" />
                </div>
        </div>
    </div>
    <div class="card-footer bg-info text-center text-white">
        <form asp-action="Delete">
            <input type="hidden" asp-for="InstituicaoID" />
            <input type="submit" value="Remover Instituição" class="btn btn-light" />
            <a asp-action="Index" class="btn btn-info">Retornar àlistagem de instituições
            </a>
        </form>
    </div>
</div>
@section ScriptPage {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Primeiro CRUD/Views/Instituicao/Details.cshtml
@model Primeiro_CRUD.Models.Instituicao
@{
    Layout = "_LayoutIES";
}
@section Styles {
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/datatables/css/jquerydataTables.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
              asp-fallback-test-class="sr-only" 
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
    </environment>
}
<div class="card-block">
    <div class="card-header text-white bg-secondary text-center h1">
    Exibindo uma instituição existente
    </div>
    <div class="card-body">
        <div class="form-group">
            <label asp-for="InstituicaoID" class="control-label"></label>
            <br/>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class="fa fa-key" aria-hidden="true"></i>
                    </span>
                </div>
                <input asp-for="InstituicaoID" class="form-control" disabled="disabled" />
            </div>
            <label asp-for="Nome" class="control-label"></label>
            <br />
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                    </span>
                </div>
                <input asp-for="Nome" class="form-control" disabled="disabled" />
            </div>
            <label asp-for="Endereco" class="control-label"></label>
                <br />
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fa fa-address-card-o" aria-hidden="true"></i>
                        </span>
                    </div>
                    <input asp-for="Endereco" class="form-control" disabled="disabled" />
                </div>
        </div>
    </div>
    <div class="card-footer bg-info text-center text-white">
        <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model.InstituicaoID">Alterar</a> |
        <a asp-action="Index" class="btn btn-warning">
            Retornar à listagem de instituições
        </a>
    </div>
</div>

Primeiro CRUD/Views/Instituicao/Edit.cshtml
@model Primeiro_CRUD.Models.Instituicao

@{
    Layout = "_LayoutIES";
}
<div class="card-block">
    <div class="card-header text-white bg-secondary text-center h1">
        Alterando uma instituição existente
    </div>
    <div class="card-body">
        <form asp-action="Edit">
            <input type="hidden" asp-for="InstituicaoID" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class=" text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group text-center h3">
                <input type="submit" value="Atualizar Instituição" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-warning">Retornar à listagem de instituições</a>
            </div>
        </form>
        <div class="card-footer bg-info text-center text-white">
            Informe os dados acima e/ou clique em um dos botões de ação
        </div>
    </div>
</div>
@section ScriptPage {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Primeiro CRUD/Views/Instituicao/Index.cshtml
@model IEnumerable<Primeiro_CRUD.Models.Instituicao>
@{
    Layout = "_LayoutIES";
}
@section Styles {
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"
              asp-fallback-href="~/lib/datatables/css/jquery.dataTables.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
}
<div class="card-block">
    <div class="card-header text-white bg-primary text-center h1">
        Instituições Registradas
    </div>
    <div class="card-body">
        <table id="tabela_instituicoes">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.InstituicaoID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Endereco)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.InstituicaoID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Endereco)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.InstituicaoID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.InstituicaoID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.InstituicaoID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer bg-success text-center">
        <a asp-action="Create" class="btn-success">Criar uma nova instituição </a>
    </div>
</div>

@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

@section ScriptPage {
    <environment include="Development">
        <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"
                asp-fallback-src="~/lib/datatables/js/jquery.dataTables.min.js">
        </script>
    </environment>
    <script type="text/javascript">
    $(document).ready(function () { $('#tabela_instituicoes').DataTable(); });
    </script>
}

Primeiro CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Primeiro_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Primeiro_CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Primeiro_CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Primeiro CRUD/Views/Shared/_LayoutIES.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Primeiro Crud</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test
              -property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap-grid.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test
              -property="position" asp-fallback-test-value="absolute" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-light bg-primary navbar-fixed-top">
        <div class="container-fluid">
            <div class="row">
                <div class="navbar-header">
                    <img class="media-heading" src="~/images/aspnet-core-mvc-logo.png" width="45" height="45" alt="">
                </div>
                <div>
                    <ul class="nav navbar-nav navbar-light">
                        <li class="navbar-brand">
                            &nbsp;&nbsp;&nbsp;ASP.NET Core MVC
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            <div class="col-2">
                <nav class="nav flex-column bg-transparent" style="margin-left:40px;">
                    <div class="row">
                        <a class="nav-link active" asp-controller="Instituicao" asp-action="Index">
                            <img src="~/images/instituicao-logo.png" width="30" height="30" alt="">Instituições
                        </a>
                    </div>
                </nav>
            </div>
            <div class="col-10">
                @RenderBody()
            </div>
        </div>
    </div>
    <nav class="navbar fixed-bottom" style="background-color: #e3f2fd; margin-top:20px;">
        <a class="navbar-brand" href="#">
            Matheus Romeike Kauva
        </a>
    </nav>
    <environment include="Development">
        <script src="~/lib/jquery/jquery.slim.min.js"></script>
        <script src="~/lib/popper.js//umd/popper.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
                asp-fallback-src="~/lib/popper.js/umd/popper.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.slim.min.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js">
        </script>
    </environment>

    @RenderSection("ScriptPage", required: false)
</body>
</html>